### ISSUE TITLE
Error System can't find the File

### ISSUE THREAD

**Issue by Luro02** [astronautlevel2/FontTool#4]
My Command:
 >python FontTool.py -font CF.bcfnt

My Command Line gives me the following:

>Your warranty ends here! Make backups of your NAND before you install this!
>load: romfs/cbf_std.bcfnt.lz
>load: ncchheader.bin
>load: romfs-mod.bin
>00000028
>Traceback (most recent call last):
>  File "FontTool.py", line 105, in <module>
>    runCmd(["make_cia", "-v", "-o", "%s.cia" % output, "--content0=%s.cfa" % output,  "--index_0=0"])
>  File "FontTool.py", line 31, in runCmd
>    process = subprocess.Popen(cmd)
>  File "C:\Python27\lib\subprocess.py", line 390, in __init__
>    errread, errwrite)
>  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
>    startupinfo)
>WindowsError: [Error 2] The System can't find the File

My Folder:
![folder](https://cloud.githubusercontent.com/assets/24826124/23268409/ef67b87a-f9ed-11e6-937b-32a30f5e876f.jpg)

**Comment by cmashinho** [comment]
Try write full path to font in your command.

**Comment by Luro02** [comment]
Like this ?: (I changed the Name)
>python FontTool.py -font C:\Users\Lucas\Desktop\FontTool-master\Font.bcfnt

Still the same Error (the .cfa gets generated)

**Comment by Luro02** [comment]
How can I get the xor Thing ? (0004009B00014002.Main.romfs.xorpad)
The Command seems to fail in Line 71

**Comment by Luro02** [comment]
Omfg fixed it -.-
# You have to drag the following Files into your Folder:
3dstool.exe
ctrtool.exe
make_cia.exe
makerom.exe

I forgot make_cia.exe -.-
